# Generated by Django 4.2.2 on 2023-06-09 07:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
